//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLaboratorioEnmanuel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleEntrada
    {
        public int Id { get; set; }
        public int Cantidad { get; set; }
        public Nullable<System.DateTime> FechaEntrada { get; set; }
        public Nullable<int> IdInsumo { get; set; }
        public Nullable<decimal> Costo { get; set; }
    
        public virtual Insumos Insumos { get; set; }
    }
}
