//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLaboratorioEnmanuel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleOrden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleOrden()
        {
            this.Resultado = new HashSet<Resultado>();
        }
    
        public int Id { get; set; }
        public string TipoExamen { get; set; }
        public Nullable<int> IdOrden { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> PerfilExamenId { get; set; }
    
        public virtual PerfilExamen PerfilExamen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resultado> Resultado { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Orden Orden { get; set; }
    }
}
