//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLaboratorioEnmanuel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resultado()
        {
            this.Salida = new HashSet<Salida>();
        }
    
        public int Id { get; set; }
        public string NombExamen { get; set; }
        public string Resultado1 { get; set; }
        public string ValoresNormales { get; set; }
        public string Unidad { get; set; }
        public string ValorReferencia { get; set; }
        public Nullable<int> IdDetalleOrden { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salida> Salida { get; set; }
        public virtual DetalleOrden DetalleOrden { get; set; }
    }
}
