//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLaboratorioEnmanuel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salida
    {
        public int Id { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public Nullable<int> IdInsumos { get; set; }
        public Nullable<int> IdResultado { get; set; }
    
        public virtual Resultado Resultado { get; set; }
        public virtual Insumos Insumos { get; set; }
    }
}
